#!/usr/bin/bash

CURDIR=$(pwd)

# link directories of configs
ln -si "$CURDIR"/dunst ~/.config/dunst
ln -si "$CURDIR"/lxde ~/.config/lxsession/LXDE
ln -si "$CURDIR"/openbox ~/.config/openbox
ln -si "$CURDIR"/termite ~/.config/termite

# link vim to locations for both nvim and vim
ln -si "$CURDIR"/vim ~/.vim
ln -si "$CURDIR"/vim/vimrc "$CURDIR"/vim/init.vim
ln -si "$CURDIR"/vim ~/.config/nvim

# link each script in scripts into .local/bin
for script in "$CURDIR"/scripts/*; do
    ln -si "$CURDIR"/scripts/"$(basename "$script")" ~/.local/bin/"$(basename "$script")"
done

# link other config files
ln -si "$CURDIR"/bash_profile ~/.bash_profile
ln -si "$CURDIR"/bashrc ~/.bashrc
ln -si "$CURDIR"/profile ~/.profile
ln -si "$CURDIR"/inputrc ~/.inputrc
ln -si "$CURDIR"/tmux.conf ~/.tmux.conf
ln -si "$CURDIR"/conky.conf ~/.config/conky/conky.conf
ln -si "$CURDIR"/Xresources ~/.Xresources
ln -si "$CURDIR"/git-prompt.sh ~/.git-prompt.sh
ln -si "$CURDIR"/gitconfig ~/.gitconfig
ln -si "$CURDIR"/gitignore ~/.gitignore
