#!/bin/bash
BACKGROUND=#3E3E3E
TEXT=#FFFFFF
INACTIVE=#4B6849
FOCUS=#7EAE7A
FONT="pango:Anonymous Pro 12"

j4-dmenu-desktop --term="termite" --no-generic --use-xdg-de --dmenu=\
"rofi -dmenu -i -p 'run:' -terminal termite -fuzzy -separator-style none -hide-scrollbar \
-opacity "80" -eh 1 -location 0 -lines 10 -width 40 -bw 0 -font '$FONT' \
-color-enabled -color-window '$BACKGROUND, $BACKGROUND'\
-color-enabled -color-normal '$BACKGROUND, $TEXT, $BACKGROUND, $FOCUS, $BACKGROUND' \
-color-enabled -color-urgent '$BACKGROUND, $TEXT, $BACKGROUND, $BACKGROUND, $BACKGROUND' \
-color-enabled -color-active '$BACKGROUND, $TEXT, $BACKGROUND, $BACKGROUND, $BACKGROUND'"
